global:
  qsname: quickstart-microsoft-rdgateway
  owner: quickstart-eng@amazon.com
  marketplace-ami: false
  reporting: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-west-1
    - us-west-2
  cis3bucket:  s3://quickstart-ci-bucket

tests:
  template1:
    template_file: Template_1_RDGW_2012.template
    parameter_input: Template_1_RDGW_2012.json
# Disabled template2 as it requires an existing VPC.
# This will eventually be rewritten to include a master template with nesting.
#  template2:
#    template_file: Template_2_RDGW_2012.template
#    parameter_input: Template_2_RDGW_2012.json
